### PR TITLE
attempt to switch to use portable FcntlFlock

### PR DESCRIPTION
**Pull request by ppbrown**
Hi Dan,
Here is some code that compiles cleanly, and uses the portable function.
Unfortunately, it does NOT pass your test code. I'm not sure why. 
Maybe you would be willing to take a look?

### CODE REVIEW

**Comment by danjacques** [comment]
Ah cool. At the moment, Travis is failing b/c of formatting:

```
these files are improperly formatted, please run: gofmt -w -s .
fslock/lock_posix.go
```

**Comment by danjacques** [comment]
(Well, that and a `pre-commit-go` issue that I'm working out on the lower Go test versions, but we can ignore that for now)

**Comment by danjacques** [comment]
I did a little reading on `fcntl`'s `flock` method, and it looks like the problem is that the requested `flock` mode has to match the read/write mode of the open file. Locally, I fixed this by having the [initial `OpenFile` call](https://github.com/danjacques/gofslock/blob/041460b11d7ed31ae90345a6c9e26a3532a2e7f9/fslock/lock_posix.go#L183) use `O_RDWR` instead of `O_RDWR`.

After making this change, the build passed the test suite on my local Linux box using `-cpu=1,2,4,8`, which is great! Would you mind making this change in your pull request?

If all's looking well, I will still need to test this on FreeBSD and Mac, which may take time, as I have less access to those resources than I used to. I'll keep you posted.

**Comment by ppbrown** [comment]
you mean in lock_posix.go?
okay.
i guess I need to make a new pull request..

**Comment by ppbrown** [comment]
nope. guess I dont need to make a new pull. cool.
still has issues though.  "too many open files". 
but.. that is apparently, becuase you randomly picked 256. 
and go by default uses OLD stdlib. and/or has old default ulimit on fd of 256.
changing count to 100 makes it work. So I'll be committing that change too.

**Comment by ppbrown** [comment]
to be clear: it now tests clean on solaris!

**Comment by danjacques** [comment]
Great!

(To be clear, 256 wasn't *random*; it was a limit that worked on all platforms that I tested on and Travis. I originally picked a much larger number, but Travis wasn't having any of that.)

**Comment by ppbrown** [comment]
256 limit on Solaris

**Comment by ppbrown** [comment]
technically, 200 would most likely work as well. but... 200? really???
:-}

**Comment by danjacques** [comment]
For this sort of concurrency test, more processes = more eyes to look for weird concurrency-related edge cases. I also built the tests to try and trigger Go's race detector when an invariant is violated, but some aspects of it (e.g., subprocess coordination) don't leverage that so well.

Anyway, 100 is fine :)

**Comment by danjacques** [comment]
It looks good on my Linux and Mac tests, too.

There is a compile error on my BSD box that makes me wonder if I ever actually got it to work, and a concurrency error there that exists on HEAD too, so I'll deal with that elsewhere.

I'm going to go ahead and accept this PR. Thanks for taking the time and working with me, and happy Solarising!

**Comment by danjacques** [comment]
Oh I guess I have to have it open to merge?

**Comment by danjacques** [comment]
Yep, OK g2g.

**Comment by ppbrown** [comment]
lol.
thanks for accepting the patch :)

**Pull request merged**
